
/* A Bison parser, made by GNU Bison 2.4.1.  */

/* Skeleton implementation for Bison's Yacc-like parsers in C
   
      Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.
   
   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "2.4.1"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1

/* Using locations.  */
#define YYLSP_NEEDED 0



/* Copy the first part of user declarations.  */

/* Line 189 of yacc.c  */
#line 1 ".\\semantic.y"

    #include <stdio.h>
    #include <stdlib.h>
    #include <unistd.h>
    #include <math.h>
    #include <string.h>
    #include "hashtbl.h"
    #include "AST.h"
    #include "semantic.tab.h"

    #define TYPE_INT    1
    #define TYPE_FLOAT  2
    #define TYPE_CHAR   3
    #define TYPE_STRING 4
    #define TYPE_VOID   5
    
    HASHTBL *hashtbl; /* define hashtable */ 
    int scope = 0;      //managing global scopes for the hashtable and the user to know where it ends 
    int error_count = 0;    //error counter
    extern FILE *yyin;      //file pointer for yyin defined in lex.yy.c, used to open the files
    extern int yylex();     //lexer function generated by flex returns integer tokens each time it is called representing different token types
    extern void yyterminate();  //used to stop lexer
    void yyerror(const char *s);    //custom error handler to terminate program when necessary
    /* Example definitions. You might refine these based on your type system. */

    int predicate_check_type_compatibility(struct ASTNode *node1, struct ASTNode *node2)
 {
    /* Assume hashtbl_get returns NULL if the identifier is not found in the given scope */
    return (hashtbl_get(hashtbl, current_scope) == NULL);
}

int predicate_check_type_compatibility(int type1, int type2) {
    /* Simple example: require that the types match exactly.
    You may want to allow promotion from int to float, etc. */
    return (type1 == type2);
}

int predicate_arithmetic_result(int type1, int type2) {
    if (type1 == type2) {
        return type1;  /* Same type => result is of that type */
    }
    /* Allow, for instance, mixing int and float by returning float */
    else if ((type1 == TYPE_INT && type2 == TYPE_FLOAT) ||
             (type1 == TYPE_FLOAT && type2 == TYPE_INT)) {
        return TYPE_FLOAT;
    }
    /* Otherwise, error. Return -1 to indicate type error */
    else {
        return -1;
    }
}

int lookupType(const char *typeName) {
    int type = hashtbl_lookup_type(hashtbl, typeName);
    if (type != 0) { // assuming 0 means "not found"
        return type;
    }
    /* Fallback for built-in types */
    if (strcmp(typeName, "int") == 0) {
        return TYPE_INT;
    } else if (strcmp(typeName, "float") == 0) {
        return TYPE_FLOAT;
    } else if (strcmp(typeName, "char") == 0) {
        return TYPE_CHAR;
    } else if (strcmp(typeName, "string") == 0) {
        return TYPE_STRING;
    } else if (strcmp(typeName, "void") == 0) {
        return TYPE_VOID;
    } else {
        fprintf(stderr, "Error: Unknown type name '%s'\n", typeName);
        exit(EXIT_FAILURE);
    }
}

void hashtbl_insert_debug(const char *id, int scope) {
        printf("Inserting '%s' into hashtable at scope %d...\n", id, scope);
        hashtbl_insert(hashtbl, id, NULL, scope);
    }

ASTNode* createASTNode(ASTNodeType type, const char *value, int intValue, float floatValue, char charValue);
void addChild(ASTNode *parent, ASTNode *child);
void addSibling(ASTNode *node, ASTNode *sibling);
void printAST(ASTNode *node, int level);
void freeAST(ASTNode *node);



/* Line 189 of yacc.c  */
#line 161 "semantic.tab.c"

/* Enabling traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 0
#endif

/* Enabling the token table.  */
#ifndef YYTOKEN_TABLE
# define YYTOKEN_TABLE 0
#endif


/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     T_EOF = 0,
     T_TYPEDEF = 258,
     T_CHAR = 259,
     T_INT = 260,
     T_FLOAT = 261,
     T_STRING = 262,
     T_CLASS = 263,
     T_PRIVATE = 264,
     T_PROTECTED = 265,
     T_PUBLIC = 266,
     T_VOID = 267,
     T_STATIC = 268,
     T_UNION = 269,
     T_ENUM = 270,
     T_LIST = 271,
     T_CONTINUE = 272,
     T_BREAK = 273,
     T_IF = 274,
     T_ELSE = 275,
     T_WHILE = 276,
     T_FOR = 277,
     T_SWITCH = 278,
     T_CASE = 279,
     T_DEFAULT = 280,
     T_RETURN = 281,
     T_LENGTH = 282,
     T_NEW = 283,
     T_CIN = 284,
     T_COUT = 285,
     T_MAIN = 286,
     T_THIS = 287,
     T_ID = 288,
     T_ICONST = 289,
     T_FCONST = 290,
     T_CCONST = 291,
     T_SCONST = 292,
     T_OROP = 293,
     T_ANDOP = 294,
     T_EQUOP = 295,
     T_RELOP = 296,
     T_ADDOP = 297,
     T_MULOP = 298,
     T_NOTOP = 299,
     T_INCDEC = 300,
     T_SIZEOP = 301,
     T_LISTFUNC = 302,
     T_LPAREN = 303,
     T_RPAREN = 304,
     T_SEMI = 305,
     T_DOT = 306,
     T_COMMA = 307,
     T_ASSIGN = 308,
     T_COLON = 309,
     T_LBRACK = 310,
     T_RBRACK = 311,
     T_REFER = 312,
     T_LBRACE = 313,
     T_RBRACE = 314,
     T_METH = 315,
     T_INP = 316,
     T_OUT = 317,
     LOWER_THAN_ELSE = 318
   };
#endif



#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
{

/* Line 214 of yacc.c  */
#line 88 ".\\semantic.y"

    int ival;      /* integer literal values or type codes */
    float fval;    /* floating point literal values */
    char cval;     /* character literal values */
    char* sval;    /* string literal values, identifier names, etc. */
    int type;      /* type information (e.g., TYPE_INT, TYPE_FLOAT, etc.) */
    struct ASTNode* ast;
    int intValue;
    float floatValue;
    char* stringValue;



/* Line 214 of yacc.c  */
#line 275 "semantic.tab.c"
} YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
#endif


/* Copy the second part of user declarations.  */


/* Line 264 of yacc.c  */
#line 287 "semantic.tab.c"

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 yytype_uint8;
#else
typedef unsigned char yytype_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 yytype_int8;
#elif (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
typedef signed char yytype_int8;
#else
typedef short int yytype_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 yytype_uint16;
#else
typedef unsigned short int yytype_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 yytype_int16;
#else
typedef short int yytype_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(msgid) dgettext ("bison-runtime", msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(msgid) msgid
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(e) ((void) (e))
#else
# define YYUSE(e) /* empty */
#endif

/* Identity function, used to suppress warnings about constant conditions.  */
#ifndef lint
# define YYID(n) (n)
#else
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static int
YYID (int yyi)
#else
static int
YYID (yyi)
    int yyi;
#endif
{
  return yyi;
}
#endif

#if ! defined yyoverflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined _STDLIB_H && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#     ifndef _STDLIB_H
#      define _STDLIB_H 1
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's `empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (YYID (0))
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined _STDLIB_H \
       && ! ((defined YYMALLOC || defined malloc) \
	     && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef _STDLIB_H
#    define _STDLIB_H 1
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined _STDLIB_H && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined _STDLIB_H && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined yyoverflow || YYERROR_VERBOSE */


#if (! defined yyoverflow \
     && (! defined __cplusplus \
	 || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yytype_int16 yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

/* Copy COUNT objects from FROM to TO.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(To, From, Count) \
      __builtin_memcpy (To, From, (Count) * sizeof (*(From)))
#  else
#   define YYCOPY(To, From, Count)		\
      do					\
	{					\
	  YYSIZE_T yyi;				\
	  for (yyi = 0; yyi < (Count); yyi++)	\
	    (To)[yyi] = (From)[yyi];		\
	}					\
      while (YYID (0))
#  endif
# endif

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)				\
    do									\
      {									\
	YYSIZE_T yynewbytes;						\
	YYCOPY (&yyptr->Stack_alloc, Stack, yysize);			\
	Stack = &yyptr->Stack_alloc;					\
	yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
	yyptr += yynewbytes / sizeof (*yyptr);				\
      }									\
    while (YYID (0))

#endif

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  3
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   863

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  64
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  89
/* YYNRULES -- Number of rules.  */
#define YYNRULES  186
/* YYNRULES -- Number of states.  */
#define YYNSTATES  356

/* YYTRANSLATE(YYLEX) -- Bison symbol number corresponding to YYLEX.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   318

#define YYTRANSLATE(YYX)						\
  ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[YYLEX] -- Bison symbol number corresponding to YYLEX.  */
static const yytype_uint8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
      45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
      55,    56,    57,    58,    59,    60,    61,    62,    63
};

#if YYDEBUG
/* YYPRHS[YYN] -- Index of the first RHS symbol of rule number YYN in
   YYRHS.  */
static const yytype_uint16 yyprhs[] =
{
       0,     0,     3,     7,     8,    11,    12,    14,    16,    18,
      20,    22,    24,    31,    33,    35,    37,    39,    41,    43,
      45,    47,    48,    51,    52,    56,    59,    64,    68,    73,
      76,    79,    80,    82,    86,    90,    94,    98,   102,   106,
     110,   113,   116,   119,   122,   125,   127,   132,   137,   142,
     144,   148,   152,   154,   159,   163,   168,   171,   173,   177,
     179,   183,   185,   187,   188,   190,   192,   194,   196,   200,
     204,   206,   211,   216,   219,   220,   224,   227,   230,   233,
     236,   237,   239,   241,   243,   245,   249,   253,   257,   259,
     263,   267,   271,   274,   276,   278,   280,   283,   286,   291,
     295,   300,   303,   305,   308,   312,   317,   321,   325,   327,
     330,   332,   334,   335,   341,   342,   348,   349,   355,   360,
     365,   370,   373,   378,   381,   383,   386,   390,   393,   395,
     397,   398,   404,   409,   411,   412,   415,   417,   419,   421,
     423,   425,   427,   429,   431,   433,   436,   439,   441,   444,
     447,   454,   457,   458,   459,   466,   467,   478,   480,   481,
     482,   489,   493,   495,   498,   500,   502,   503,   506,   508,
     513,   518,   522,   527,   532,   536,   541,   546,   550,   552,
     554,   558,   560,   562,   563,   568,   573
};

/* YYRHS -- A `-1'-separated list of the rules' RHS.  */
static const yytype_int16 yyrhs[] =
{
      65,     0,    -1,    66,   151,     0,    -1,    -1,    66,    67,
      -1,    -1,    68,    -1,    74,    -1,    87,    -1,   108,    -1,
     109,    -1,   112,    -1,     3,    69,    71,    33,    72,    50,
      -1,    70,    -1,    33,    -1,     4,    -1,     5,    -1,     6,
      -1,     7,    -1,    12,    -1,    16,    -1,    -1,    72,    73,
      -1,    -1,    55,    34,    56,    -1,    55,    56,    -1,    15,
      33,    75,    50,    -1,    58,    76,    59,    -1,    76,    52,
      33,    77,    -1,    33,    77,    -1,    53,    78,    -1,    -1,
      79,    -1,    58,    86,    59,    -1,    79,    38,    79,    -1,
      79,    39,    79,    -1,    79,    40,    79,    -1,    79,    41,
      79,    -1,    79,    42,    79,    -1,    79,    43,    79,    -1,
      44,    79,    -1,    42,    79,    -1,    46,    79,    -1,    45,
      80,    -1,    80,    45,    -1,    80,    -1,    80,    48,    83,
      49,    -1,    27,    48,    81,    49,    -1,    28,    48,    81,
      49,    -1,    84,    -1,    48,    81,    49,    -1,    48,    70,
      49,    -1,    85,    -1,    80,    55,    81,    56,    -1,    80,
      51,    33,    -1,    47,    48,    81,    49,    -1,   125,    33,
      -1,    32,    -1,    81,    52,    81,    -1,    82,    -1,    80,
      53,    82,    -1,    79,    -1,    81,    -1,    -1,    36,    -1,
      34,    -1,    35,    -1,    37,    -1,    55,    83,    56,    -1,
      86,    52,    78,    -1,    78,    -1,     8,    33,    88,    50,
      -1,    89,    58,    90,    59,    -1,    54,    33,    -1,    -1,
      90,    91,    92,    -1,    91,    92,    -1,     9,    54,    -1,
      10,    54,    -1,    11,    54,    -1,    -1,    93,    -1,   101,
      -1,    94,    -1,    97,    -1,    69,    95,    50,    -1,    69,
      95,     1,    -1,    95,    52,    96,    -1,    96,    -1,    71,
      33,    72,    -1,    14,    98,    50,    -1,    58,    99,    59,
      -1,    99,   100,    -1,   100,    -1,    94,    -1,   102,    -1,
     103,    50,    -1,   107,    50,    -1,   104,    48,   105,    49,
      -1,    69,    71,    33,    -1,   105,    52,    69,   106,    -1,
      69,   106,    -1,    57,    -1,    71,    72,    -1,   104,    48,
      49,    -1,    14,    33,    98,    50,    -1,    69,   110,    50,
      -1,   110,    52,   111,    -1,   111,    -1,    96,    77,    -1,
     102,    -1,   113,    -1,    -1,   117,    58,   114,   123,    59,
      -1,    -1,   122,    58,   115,   123,    59,    -1,    -1,   107,
      58,   116,   123,    59,    -1,   118,    48,   120,    49,    -1,
     104,    48,   120,    49,    -1,    69,    71,   119,    33,    -1,
      33,    60,    -1,   120,    52,    69,   121,    -1,    69,   121,
      -1,    96,    -1,    57,    33,    -1,   118,    48,    49,    -1,
     124,   126,    -1,   124,    -1,   126,    -1,    -1,   124,   125,
      69,    95,    50,    -1,   125,    69,    95,    50,    -1,    13,
      -1,    -1,   126,   127,    -1,   127,    -1,   128,    -1,   129,
      -1,   131,    -1,   133,    -1,   136,    -1,   143,    -1,   144,
      -1,   149,    -1,    17,    50,    -1,    18,    50,    -1,    50,
      -1,    81,    50,    -1,     1,    50,    -1,    19,    48,    81,
      49,   127,   130,    -1,    20,   127,    -1,    -1,    -1,    21,
      48,    81,    49,   132,   127,    -1,    -1,    22,    48,   135,
      50,   135,    50,   135,    49,   134,   127,    -1,    81,    -1,
      -1,    -1,    23,    48,    81,    49,   137,   138,    -1,    58,
     139,    59,    -1,   142,    -1,   124,   140,    -1,   124,    -1,
     140,    -1,    -1,   140,   141,    -1,   141,    -1,    24,    84,
      54,   141,    -1,    24,    84,    54,   126,    -1,    25,    54,
     126,    -1,    24,    84,    54,   142,    -1,    24,    84,    54,
     127,    -1,    26,   135,    50,    -1,    29,    61,   145,    50,
      -1,    30,    62,   147,    50,    -1,   145,    61,   146,    -1,
     146,    -1,    80,    -1,   147,    62,   148,    -1,   148,    -1,
      81,    -1,    -1,    58,   150,   123,    59,    -1,   152,    58,
     123,    59,    -1,     5,    31,    48,    49,    -1
};

/* YYRLINE[YYN] -- source line where rule number YYN was defined.  */
static const yytype_uint16 yyrline[] =
{
       0,   194,   194,   201,   204,   208,   211,   213,   214,   215,
     216,   217,   220,   237,   239,   245,   246,   247,   248,   249,
     252,   253,   256,   261,   264,   265,   268,   279,   282,   283,
     286,   287,   290,   291,   294,   295,   296,   297,   298,   305,
     312,   313,   314,   315,   316,   317,   318,   319,   320,   321,
     322,   323,   324,   327,   328,   336,   337,   342,   345,   346,
     349,   358,   361,   362,   365,   365,   365,   365,   368,   371,
     372,   375,   385,   388,   389,   392,   393,   396,   397,   398,
     399,   402,   403,   406,   407,   411,   412,   415,   416,   419,
     429,   432,   435,   436,   439,   442,   445,   446,   449,   452,
     462,   463,   466,   467,   470,   473,   484,   487,   488,   491,
     494,   495,   498,   498,   499,   499,   500,   500,   503,   504,
     507,   510,   513,   514,   517,   518,   521,   524,   525,   526,
     527,   530,   531,   534,   535,   538,   539,   542,   543,   545,
     546,   547,   548,   549,   550,   551,   552,   553,   557,   558,
     561,   573,   574,   577,   577,   580,   580,   583,   584,   587,
     587,   590,   591,   594,   595,   596,   597,   600,   601,   604,
     605,   606,   609,   610,   613,   616,   617,   620,   621,   624,
     627,   628,   631,   634,   634,   637,   646
};
#endif

#if YYDEBUG || YYERROR_VERBOSE || YYTOKEN_TABLE
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"EOF\"", "error", "$undefined", "\"typedef\"", "\"char\"", "\"int\"",
  "\"float\"", "\"string\"", "\"class\"", "\"private\"", "\"protected\"",
  "\"public\"", "\"void\"", "\"static\"", "\"union\"", "\"enum\"",
  "\"list\"", "\"continue\"", "\"break\"", "\"if\"", "\"else\"",
  "\"while\"", "\"for\"", "\"switch\"", "\"case\"", "\"default\"",
  "\"return\"", "\"length\"", "\"new\"", "\"cin\"", "\"cout\"", "\"main\"",
  "\"this\"", "\"id\"", "\"iconst\"", "\"fconst\"", "\"cconst\"",
  "\"sconst\"", "\"||\"", "\"&&\"", "\"==\"", "\">\"", "\"+\"", "\"*\"",
  "\"!\"", "\"++\"", "\"sizeop\"", "\"listfunc\"", "\"(\"", "\")\"",
  "\";\"", "\".\"", "\",\"", "\"=\"", "\":\"", "\"[\"", "\"]\"",
  "\"refer\"", "\"{\"", "\"}\"", "\"meth\"", "\"<<\"", "\">>\"",
  "LOWER_THAN_ELSE", "$accept", "program", "global_declarations",
  "global_declaration", "typedef_declaration", "typename", "standard_type",
  "listspec", "dims", "dim", "enum_declaration", "enum_body", "id_list",
  "initializer", "init_value", "expression", "variable",
  "general_expression", "assignment", "expression_list", "constant",
  "listexpression", "init_values", "class_declaration", "class_body",
  "parent", "members_methods", "access", "member_or_method", "member",
  "var_declaration", "variabledefs", "variabledef", "anonymous_union",
  "union_body", "fields", "field", "method", "short_func_declaration",
  "short_par_func_header", "func_header_start", "parameter_types",
  "pass_list_dims", "nopar_func_header", "union_declaration",
  "global_var_declaration", "init_variabledefs", "init_variabledef",
  "func_declaration", "full_func_declaration", "$@1", "$@2", "$@3",
  "full_par_func_header", "class_func_header_start", "func_class",
  "parameter_list", "pass_variabledef", "nopar_class_func_header",
  "decl_statements", "declarations", "decltype", "statements", "statement",
  "expression_statement", "if_statement", "if_tail", "while_statement",
  "$@4", "for_statement", "$@5", "optexpr", "switch_statement", "$@6",
  "switch_tail", "decl_cases", "casestatements", "casestatement",
  "single_casestatement", "return_statement", "io_statement", "in_list",
  "in_item", "out_list", "out_item", "comp_statement", "$@7",
  "main_function", "main_header", 0
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[YYLEX-NUM] -- Internal token number corresponding to
   token YYLEX-NUM.  */
static const yytype_uint16 yytoknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,   280,   281,   282,   283,   284,
     285,   286,   287,   288,   289,   290,   291,   292,   293,   294,
     295,   296,   297,   298,   299,   300,   301,   302,   303,   304,
     305,   306,   307,   308,   309,   310,   311,   312,   313,   314,
     315,   316,   317,   318
};
# endif

/* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const yytype_uint8 yyr1[] =
{
       0,    64,    65,    65,    66,    66,    67,    67,    67,    67,
      67,    67,    68,    69,    69,    70,    70,    70,    70,    70,
      71,    71,    72,    72,    73,    73,    74,    75,    76,    76,
      77,    77,    78,    78,    79,    79,    79,    79,    79,    79,
      79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
      79,    79,    79,    80,    80,    80,    80,    80,    81,    81,
      82,    82,    83,    83,    84,    84,    84,    84,    85,    86,
      86,    87,    88,    89,    89,    90,    90,    91,    91,    91,
      91,    92,    92,    93,    93,    94,    94,    95,    95,    96,
      97,    98,    99,    99,   100,   101,   102,   102,   103,   104,
     105,   105,   106,   106,   107,   108,   109,   110,   110,   111,
     112,   112,   114,   113,   115,   113,   116,   113,   117,   117,
     118,   119,   120,   120,   121,   121,   122,   123,   123,   123,
     123,   124,   124,   125,   125,   126,   126,   127,   127,   127,
     127,   127,   127,   127,   127,   127,   127,   127,   128,   128,
     129,   130,   130,   132,   131,   134,   133,   135,   135,   137,
     136,   138,   138,   139,   139,   139,   139,   140,   140,   141,
     141,   141,   142,   142,   143,   144,   144,   145,   145,   146,
     147,   147,   148,   150,   149,   151,   152
};

/* YYR2[YYN] -- Number of symbols composing right hand side of rule YYN.  */
static const yytype_uint8 yyr2[] =
{
       0,     2,     3,     0,     2,     0,     1,     1,     1,     1,
       1,     1,     6,     1,     1,     1,     1,     1,     1,     1,
       1,     0,     2,     0,     3,     2,     4,     3,     4,     2,
       2,     0,     1,     3,     3,     3,     3,     3,     3,     3,
       2,     2,     2,     2,     2,     1,     4,     4,     4,     1,
       3,     3,     1,     4,     3,     4,     2,     1,     3,     1,
       3,     1,     1,     0,     1,     1,     1,     1,     3,     3,
       1,     4,     4,     2,     0,     3,     2,     2,     2,     2,
       0,     1,     1,     1,     1,     3,     3,     3,     1,     3,
       3,     3,     2,     1,     1,     1,     2,     2,     4,     3,
       4,     2,     1,     2,     3,     4,     3,     3,     1,     2,
       1,     1,     0,     5,     0,     5,     0,     5,     4,     4,
       4,     2,     4,     2,     1,     2,     3,     2,     1,     1,
       0,     5,     4,     1,     0,     2,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     2,     2,     1,     2,     2,
       6,     2,     0,     0,     6,     0,    10,     1,     0,     0,
       6,     3,     1,     2,     1,     1,     0,     2,     1,     4,
       4,     3,     4,     4,     3,     4,     4,     3,     1,     1,
       3,     1,     1,     0,     4,     4,     4
};

/* YYDEFACT[STATE-NAME] -- Default rule to reduce with in state
   STATE-NUM when YYTABLE doesn't specify something else to do.  Zero
   means the default is an error.  */
static const yytype_uint8 yydefact[] =
{
       5,     0,     0,     1,     0,    15,    16,    17,    18,     0,
      19,     0,     0,    14,     4,     6,    21,    13,     7,     8,
     110,     0,     0,     0,     9,    10,    11,   111,     0,     0,
       0,     0,     0,    16,    21,     0,    74,     0,     0,    20,
       0,    31,     0,   108,    96,     0,    97,   116,   112,     0,
     114,     2,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    23,     0,   134,   109,   106,    21,   104,    21,
       0,     0,     0,     0,   126,    21,     0,     0,     0,   133,
       0,     0,     0,     0,     0,     0,   134,     0,     0,     0,
       0,    57,    65,    66,    64,    67,   134,   134,   134,   134,
       0,   134,   147,    63,   183,    61,    45,     0,    59,    49,
      52,     0,     0,     0,     0,   136,   137,   138,   139,   140,
     141,   142,   143,   144,    23,   186,    73,    71,    80,    21,
      94,     0,    93,   105,    31,     0,    26,   121,    89,   120,
     134,    30,    32,    45,     0,     0,   107,   102,    23,   124,
     101,   123,    98,     0,   119,     0,     0,     0,     0,   118,
       0,   149,   145,   146,   134,   134,   134,   134,   157,     0,
     134,   134,   134,   134,    41,    40,    43,    42,   134,     0,
       0,    62,     0,     0,   134,   134,   134,   134,   134,   134,
      44,    63,     0,   134,   134,   148,   134,   185,     0,     0,
      56,    21,   135,     0,     0,     0,     0,    80,     0,     0,
      88,    91,    92,    29,     0,    27,     0,    22,    70,     0,
      56,    23,   125,   103,    21,    21,   117,   113,   115,     0,
       0,     0,     0,   174,     0,     0,   179,     0,   178,   182,
       0,   181,     0,    51,    50,    68,     0,    34,    35,    36,
      37,    38,    39,     0,    54,    60,     0,    58,    21,     0,
      12,    77,    78,    79,    72,     0,     0,    21,    76,    81,
      83,    84,    82,    95,     0,     0,    86,    85,    21,    31,
       0,    25,   134,    33,   102,    23,   100,   122,     0,   153,
     134,   159,    47,    48,   175,   134,   176,   134,    55,   184,
      46,    53,     0,   132,    75,     0,     0,     0,    87,    28,
      24,    69,   152,     0,     0,     0,   177,   180,   131,    90,
      23,    21,     0,   150,   154,   134,     0,   134,   160,   162,
     151,     0,     0,     0,     0,   134,     0,     0,   165,   168,
     155,     0,     0,     0,     0,   163,   161,   167,     0,   173,
     172,     0,     0,   156,     0,   169
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int16 yydefgoto[] =
{
      -1,     1,     2,    14,    15,   129,    17,   145,   138,   217,
      18,    61,   135,    65,   141,   105,   106,   107,   108,   182,
     109,   110,   219,    19,    56,    57,   207,   208,   268,   269,
     130,   209,   210,   271,    59,   131,   132,   272,   273,    21,
     274,    70,   150,   275,    24,    25,    42,    43,    26,    27,
      73,    77,    72,    28,    29,    63,    71,   151,    30,   111,
     112,   144,   114,   115,   116,   117,   323,   118,   313,   119,
     348,   169,   120,   315,   328,   337,   338,   339,   329,   121,
     122,   237,   238,   240,   241,   123,   183,    31,    32
};

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
#define YYPACT_NINF -252
static const yytype_int16 yypact[] =
{
      21,    45,   214,  -252,   228,  -252,    72,  -252,  -252,    51,
    -252,    91,   111,  -252,  -252,  -252,   170,  -252,  -252,  -252,
    -252,   121,   129,    87,  -252,  -252,  -252,  -252,   144,   157,
     172,   211,   190,  -252,   170,   167,   205,   212,   222,  -252,
     242,   246,   100,  -252,  -252,    67,  -252,  -252,  -252,   142,
    -252,  -252,   291,   268,   253,   274,   261,   257,   228,   266,
     307,   272,    54,   310,   708,  -252,  -252,   170,  -252,    28,
     155,   161,   291,   291,  -252,    30,   175,   291,   311,  -252,
     312,   313,   297,   319,   323,   324,   733,   330,   337,   325,
     326,  -252,  -252,  -252,  -252,  -252,   808,   808,    63,   808,
     339,   153,  -252,   758,  -252,   819,   119,   132,  -252,  -252,
    -252,   331,   347,   267,   491,  -252,  -252,  -252,  -252,  -252,
    -252,  -252,  -252,  -252,  -252,  -252,  -252,  -252,   152,   170,
    -252,    29,  -252,  -252,   246,   -21,  -252,  -252,   343,  -252,
     708,  -252,   819,   128,   366,   367,  -252,   368,   367,  -252,
    -252,  -252,  -252,   228,  -252,   228,   344,   345,   368,  -252,
     348,  -252,  -252,  -252,   808,   808,   733,   808,   357,   360,
     808,   808,    63,   808,   372,  -252,    70,  -252,   808,   362,
     194,   357,   370,   291,   808,   808,   808,   808,   808,   808,
    -252,   758,   400,   808,   808,  -252,   808,  -252,   267,   539,
       4,   170,  -252,   -33,   380,   381,   382,    50,   250,    15,
    -252,  -252,  -252,  -252,   405,  -252,    52,  -252,  -252,    -4,
    -252,  -252,  -252,   343,    41,    30,  -252,  -252,  -252,   201,
     216,   396,   217,  -252,   232,   233,    70,    57,  -252,   357,
      73,  -252,   295,  -252,  -252,  -252,   388,   248,   289,   151,
     234,   372,  -252,   399,  -252,  -252,    49,  -252,   170,   189,
    -252,  -252,  -252,  -252,  -252,   250,   212,   170,  -252,  -252,
    -252,  -252,  -252,  -252,   401,   402,  -252,  -252,   170,   246,
     403,  -252,   708,  -252,  -252,  -252,  -252,  -252,   683,  -252,
     733,  -252,  -252,  -252,  -252,    63,  -252,   808,  -252,  -252,
    -252,  -252,   208,  -252,  -252,   407,   418,    67,  -252,  -252,
    -252,  -252,   435,   683,   408,    -9,  -252,  -252,  -252,  -252,
     415,    41,   683,  -252,  -252,   783,   321,    53,  -252,  -252,
    -252,   425,   427,   321,   428,    56,   228,   424,   269,  -252,
    -252,   635,   430,   683,   228,   269,  -252,  -252,   683,  -252,
    -252,   587,   395,  -252,   443,  -252
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -252,  -252,  -252,  -252,  -252,    -2,   385,   -15,  -116,  -252,
    -252,  -252,  -252,  -124,  -126,   -57,   -46,   -74,   301,   304,
    -251,  -252,  -252,  -252,  -252,  -252,  -252,   290,   231,  -252,
    -197,  -188,   -11,  -252,   237,  -252,   369,  -252,   497,  -252,
     503,  -252,   282,   505,  -252,  -252,  -252,   444,  -252,  -252,
    -252,  -252,  -252,  -252,  -252,  -252,   466,   305,  -252,   -47,
     195,   -49,  -106,  -110,  -252,  -252,  -252,  -252,  -252,  -252,
    -252,  -157,  -252,  -252,  -252,  -252,   181,  -232,   188,  -252,
    -252,  -252,   236,  -252,   235,  -252,  -252,  -252,  -252
};

/* YYTABLE[YYPACT[STATE-NUM]].  What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule which
   number is the opposite.  If zero, do what YYDEFACT says.
   If YYTABLE_NINF, syntax error.  */
#define YYTABLE_NINF -172
static const yytype_int16 yytable[] =
{
      16,    40,    34,   113,   202,    41,   199,   142,   203,   231,
     213,   270,   168,   259,   218,   326,   276,   260,   143,    53,
     -14,    -3,   216,   113,   113,   156,   157,   180,   113,   181,
     160,   214,   223,     5,    33,     7,     8,   -14,   215,   174,
     175,    10,   177,    69,    39,     3,    39,    75,   282,   327,
     143,   143,   176,   143,   148,   283,    41,    39,   149,   204,
     205,   206,    13,   198,   149,   277,    79,   278,   270,    79,
     302,     5,    33,     7,     8,   332,    79,   333,   334,    10,
     333,   334,   342,   142,    36,   147,   280,   158,   211,   202,
     229,   230,   168,   232,   143,    91,   234,   235,   284,   239,
      13,   196,   -99,    35,   242,   301,   347,   294,   281,   264,
     100,   201,  -166,   347,   137,  -164,    68,   181,   295,   355,
     256,   192,   257,   296,    37,   194,   236,   247,   248,   249,
     250,   251,   252,   314,   113,   297,   246,    46,   143,   143,
     143,   143,   143,   143,    38,    47,     5,    33,     7,     8,
      66,   224,    67,   225,    10,   309,   311,     5,    33,     7,
       8,   204,   205,   206,   190,    10,    79,   191,   331,   223,
     192,    44,   193,   190,   194,    13,   191,    45,   312,   192,
      87,    88,   195,   194,   196,    91,    39,    92,    93,    94,
      95,    74,   187,   188,   189,    96,   258,    97,    98,    99,
     100,   101,    48,   324,   152,    49,   267,   153,   103,   285,
     154,    51,   330,   155,   149,    54,   168,     4,     5,     6,
       7,     8,     9,   239,   159,   142,    10,   155,    11,    12,
      50,   349,     5,    33,     7,     8,   143,   352,   353,   303,
      10,   278,   202,   244,   202,   354,   196,    13,    52,   236,
     288,   168,   306,   196,     5,    33,     7,     8,   318,    55,
     278,    13,    10,   267,   266,   289,   291,   308,   196,   196,
      58,     5,    33,     7,     8,    62,   188,   189,   336,    10,
      60,   292,   293,    13,   196,   196,   344,   185,   186,   187,
     188,   189,    78,   333,   334,  -134,  -134,  -134,  -134,    64,
     200,   124,   125,  -134,    79,   321,   285,   126,    80,    81,
      82,   127,    83,    84,    85,   128,   133,    86,    87,    88,
      89,    90,   136,    91,  -134,    92,    93,    94,    95,   186,
     187,   188,   189,    96,   201,    97,    98,    99,   100,   101,
     134,   102,   258,   139,   298,   164,   103,   196,    78,   104,
    -130,  -134,  -134,  -134,  -134,    92,    93,    94,    95,  -134,
      79,   161,   162,   163,    80,    81,    82,   165,    83,    84,
      85,   166,   167,    86,    87,    88,    89,    90,   170,    91,
    -134,    92,    93,    94,    95,   171,   172,   178,   173,    96,
     197,    97,    98,    99,   100,   101,    78,   102,   216,   220,
     221,   222,   103,   226,   227,   104,  -128,   228,    79,   196,
     233,   243,    80,    81,    82,   189,    83,    84,    85,  -171,
    -171,    86,    87,    88,    89,    90,   245,    91,  -134,    92,
      93,    94,    95,   254,   261,   262,   263,    96,   279,    97,
      98,    99,   100,   101,    78,   102,   290,   299,   300,   307,
     103,   320,    46,   104,  -171,   322,    79,   319,   325,   310,
      80,    81,    82,   -99,    83,    84,    85,  -170,  -170,    86,
      87,    88,    89,    90,   340,    91,  -134,    92,    93,    94,
      95,   341,   343,   346,   351,    96,   179,    97,    98,    99,
     100,   101,    78,   102,   255,   253,   304,   265,   103,    20,
     212,   104,  -170,   305,    79,    22,   286,    23,    80,    81,
      82,   146,    83,    84,    85,    76,   345,    86,    87,    88,
      89,    90,   335,    91,  -134,    92,    93,    94,    95,   350,
     287,   316,   317,    96,     0,    97,    98,    99,   100,   101,
      78,   102,     0,     0,     0,     0,   103,     0,     0,   104,
    -129,     0,    79,     0,     0,     0,    80,    81,    82,     0,
      83,    84,    85,     0,     0,    86,    87,    88,    89,    90,
       0,    91,  -134,    92,    93,    94,    95,     0,     0,     0,
       0,    96,     0,    97,    98,    99,   100,   101,    78,   102,
       0,     0,     0,     0,   103,     0,     0,   104,  -127,     0,
      79,     0,     0,     0,    80,    81,    82,     0,    83,    84,
      85,   333,   334,    86,    87,    88,    89,    90,     0,    91,
    -134,    92,    93,    94,    95,     0,     0,     0,     0,    96,
       0,    97,    98,    99,   100,   101,    78,   102,     0,     0,
       0,     0,   103,     0,     0,   104,     0,     0,    79,     0,
       0,     0,    80,    81,    82,     0,    83,    84,    85,   326,
       0,    86,    87,    88,    89,    90,     0,    91,  -134,    92,
      93,    94,    95,     0,     0,     0,     0,    96,     0,    97,
      98,    99,   100,   101,    78,   102,     0,     0,     0,     0,
     103,     0,     0,   104,     0,     0,    79,     0,     0,     0,
      80,    81,    82,     0,    83,    84,    85,     0,     0,    86,
      87,    88,    89,    90,     0,    91,  -134,    92,    93,    94,
      95,    79,     0,     0,     0,    96,     0,    97,    98,    99,
     100,   101,     0,   102,     0,    87,    88,     0,   103,     0,
      91,   104,    92,    93,    94,    95,    79,     0,     0,     0,
      96,     0,    97,    98,    99,   100,   101,     0,     0,     0,
      87,    88,     0,   103,     0,    91,   140,    92,    93,    94,
      95,    79,     0,     0,     0,    96,     0,    97,    98,    99,
     100,   101,     0,  -158,     0,    87,    88,     0,   103,     0,
      91,  -134,    92,    93,    94,    95,    79,     0,     0,     0,
      96,     0,    97,    98,    99,   100,   101,     0,     0,     0,
      87,    88,     0,   103,     0,    91,     0,    92,    93,    94,
      95,    79,     0,     0,     0,    96,     0,    97,    98,    99,
     100,   101,  -158,     0,     0,    87,    88,     0,   103,     0,
      91,     0,    92,    93,    94,    95,     0,     0,     0,     0,
      96,     0,    97,    98,    99,   100,   101,   184,   185,   186,
     187,   188,   189,   103
};

static const yytype_int16 yycheck[] =
{
       2,    16,     4,    52,   114,    16,   112,    64,   124,   166,
     134,   208,    86,   201,   140,    24,     1,    50,    64,    34,
      16,     0,    55,    72,    73,    72,    73,   101,    77,   103,
      77,    52,   148,     4,     5,     6,     7,    33,    59,    96,
      97,    12,    99,    45,    16,     0,    16,    49,    52,    58,
      96,    97,    98,    99,    69,    59,    67,    16,    69,     9,
      10,    11,    33,   112,    75,    50,    13,    52,   265,    13,
     258,     4,     5,     6,     7,   326,    13,    24,    25,    12,
      24,    25,   333,   140,    33,    57,    34,    57,    59,   199,
     164,   165,   166,   167,   140,    32,   170,   171,    57,   173,
      33,    52,    48,    31,   178,    56,   338,    50,    56,    59,
      47,   113,    59,   345,    60,    59,    49,   191,    61,   351,
     194,    51,   196,    50,    33,    55,   172,   184,   185,   186,
     187,   188,   189,   290,   183,    62,   183,    50,   184,   185,
     186,   187,   188,   189,    33,    58,     4,     5,     6,     7,
      50,   153,    52,   155,    12,   279,   282,     4,     5,     6,
       7,     9,    10,    11,    45,    12,    13,    48,   325,   285,
      51,    50,    53,    45,    55,    33,    48,    48,   288,    51,
      27,    28,    50,    55,    52,    32,    16,    34,    35,    36,
      37,    49,    41,    42,    43,    42,   198,    44,    45,    46,
      47,    48,    58,   313,    49,    48,   208,    52,    55,   224,
      49,     0,   322,    52,   225,    48,   290,     3,     4,     5,
       6,     7,     8,   297,    49,   282,    12,    52,    14,    15,
      58,   341,     4,     5,     6,     7,   282,   343,   348,    50,
      12,    52,   352,    49,   354,   351,    52,    33,    58,   295,
      49,   325,   267,    52,     4,     5,     6,     7,    50,    54,
      52,    33,    12,   265,    14,    49,    49,   278,    52,    52,
      58,     4,     5,     6,     7,    33,    42,    43,   327,    12,
      58,    49,    49,    33,    52,    52,   335,    39,    40,    41,
      42,    43,     1,    24,    25,     4,     5,     6,     7,    53,
      33,    33,    49,    12,    13,   307,   321,    33,    17,    18,
      19,    50,    21,    22,    23,    58,    50,    26,    27,    28,
      29,    30,    50,    32,    33,    34,    35,    36,    37,    40,
      41,    42,    43,    42,   336,    44,    45,    46,    47,    48,
      33,    50,   344,    33,    49,    48,    55,    52,     1,    58,
      59,     4,     5,     6,     7,    34,    35,    36,    37,    12,
      13,    50,    50,    50,    17,    18,    19,    48,    21,    22,
      23,    48,    48,    26,    27,    28,    29,    30,    48,    32,
      33,    34,    35,    36,    37,    48,    61,    48,    62,    42,
      59,    44,    45,    46,    47,    48,     1,    50,    55,    33,
      33,    33,    55,    59,    59,    58,    59,    59,    13,    52,
      50,    49,    17,    18,    19,    43,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    56,    32,    33,    34,
      35,    36,    37,    33,    54,    54,    54,    42,    33,    44,
      45,    46,    47,    48,     1,    50,    50,    59,    49,    48,
      55,    33,    50,    58,    59,    20,    13,    50,    50,    56,
      17,    18,    19,    48,    21,    22,    23,    24,    25,    26,
      27,    28,    29,    30,    49,    32,    33,    34,    35,    36,
      37,    54,    54,    59,    54,    42,   101,    44,    45,    46,
      47,    48,     1,    50,   193,   191,   265,   207,    55,     2,
     131,    58,    59,   266,    13,     2,   224,     2,    17,    18,
      19,    67,    21,    22,    23,    49,   335,    26,    27,    28,
      29,    30,   327,    32,    33,    34,    35,    36,    37,   341,
     225,   295,   297,    42,    -1,    44,    45,    46,    47,    48,
       1,    50,    -1,    -1,    -1,    -1,    55,    -1,    -1,    58,
      59,    -1,    13,    -1,    -1,    -1,    17,    18,    19,    -1,
      21,    22,    23,    -1,    -1,    26,    27,    28,    29,    30,
      -1,    32,    33,    34,    35,    36,    37,    -1,    -1,    -1,
      -1,    42,    -1,    44,    45,    46,    47,    48,     1,    50,
      -1,    -1,    -1,    -1,    55,    -1,    -1,    58,    59,    -1,
      13,    -1,    -1,    -1,    17,    18,    19,    -1,    21,    22,
      23,    24,    25,    26,    27,    28,    29,    30,    -1,    32,
      33,    34,    35,    36,    37,    -1,    -1,    -1,    -1,    42,
      -1,    44,    45,    46,    47,    48,     1,    50,    -1,    -1,
      -1,    -1,    55,    -1,    -1,    58,    -1,    -1,    13,    -1,
      -1,    -1,    17,    18,    19,    -1,    21,    22,    23,    24,
      -1,    26,    27,    28,    29,    30,    -1,    32,    33,    34,
      35,    36,    37,    -1,    -1,    -1,    -1,    42,    -1,    44,
      45,    46,    47,    48,     1,    50,    -1,    -1,    -1,    -1,
      55,    -1,    -1,    58,    -1,    -1,    13,    -1,    -1,    -1,
      17,    18,    19,    -1,    21,    22,    23,    -1,    -1,    26,
      27,    28,    29,    30,    -1,    32,    33,    34,    35,    36,
      37,    13,    -1,    -1,    -1,    42,    -1,    44,    45,    46,
      47,    48,    -1,    50,    -1,    27,    28,    -1,    55,    -1,
      32,    58,    34,    35,    36,    37,    13,    -1,    -1,    -1,
      42,    -1,    44,    45,    46,    47,    48,    -1,    -1,    -1,
      27,    28,    -1,    55,    -1,    32,    58,    34,    35,    36,
      37,    13,    -1,    -1,    -1,    42,    -1,    44,    45,    46,
      47,    48,    -1,    50,    -1,    27,    28,    -1,    55,    -1,
      32,    33,    34,    35,    36,    37,    13,    -1,    -1,    -1,
      42,    -1,    44,    45,    46,    47,    48,    -1,    -1,    -1,
      27,    28,    -1,    55,    -1,    32,    -1,    34,    35,    36,
      37,    13,    -1,    -1,    -1,    42,    -1,    44,    45,    46,
      47,    48,    49,    -1,    -1,    27,    28,    -1,    55,    -1,
      32,    -1,    34,    35,    36,    37,    -1,    -1,    -1,    -1,
      42,    -1,    44,    45,    46,    47,    48,    38,    39,    40,
      41,    42,    43,    55
};

/* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
   symbol of state STATE-NUM.  */
static const yytype_uint8 yystos[] =
{
       0,    65,    66,     0,     3,     4,     5,     6,     7,     8,
      12,    14,    15,    33,    67,    68,    69,    70,    74,    87,
     102,   103,   104,   107,   108,   109,   112,   113,   117,   118,
     122,   151,   152,     5,    69,    31,    33,    33,    33,    16,
      71,    96,   110,   111,    50,    48,    50,    58,    58,    48,
      58,     0,    58,    71,    48,    54,    88,    89,    58,    98,
      58,    75,    33,   119,    53,    77,    50,    52,    49,    69,
     105,   120,   116,   114,    49,    69,   120,   115,     1,    13,
      17,    18,    19,    21,    22,    23,    26,    27,    28,    29,
      30,    32,    34,    35,    36,    37,    42,    44,    45,    46,
      47,    48,    50,    55,    58,    79,    80,    81,    82,    84,
      85,   123,   124,   125,   126,   127,   128,   129,   131,   133,
     136,   143,   144,   149,    33,    49,    33,    50,    58,    69,
      94,    99,   100,    50,    33,    76,    50,    60,    72,    33,
      58,    78,    79,    80,   125,    71,   111,    57,    71,    96,
     106,   121,    49,    52,    49,    52,   123,   123,    57,    49,
     123,    50,    50,    50,    48,    48,    48,    48,    81,   135,
      48,    48,    61,    62,    79,    79,    80,    79,    48,    70,
      81,    81,    83,   150,    38,    39,    40,    41,    42,    43,
      45,    48,    51,    53,    55,    50,    52,    59,   125,   126,
      33,    69,   127,    72,     9,    10,    11,    90,    91,    95,
      96,    59,   100,    77,    52,    59,    55,    73,    78,    86,
      33,    33,    33,    72,    69,    69,    59,    59,    59,    81,
      81,   135,    81,    50,    81,    81,    80,   145,   146,    81,
     147,   148,    81,    49,    49,    56,   123,    79,    79,    79,
      79,    79,    79,    83,    33,    82,    81,    81,    69,    95,
      50,    54,    54,    54,    59,    91,    14,    69,    92,    93,
      94,    97,   101,   102,   104,   107,     1,    50,    52,    33,
      34,    56,    52,    59,    57,    71,   106,   121,    49,    49,
      50,    49,    49,    49,    50,    61,    50,    62,    49,    59,
      49,    56,    95,    50,    92,    98,    71,    48,    96,    77,
      56,    78,   127,   132,   135,   137,   146,   148,    50,    50,
      33,    69,    20,   130,   127,    50,    24,    58,   138,   142,
     127,   135,    84,    24,    25,   124,   125,   139,   140,   141,
      49,    54,    84,    54,   125,   140,    59,   141,   134,   127,
     142,    54,   126,   127,   126,   141
};

#define yyerrok		(yyerrstatus = 0)
#define yyclearin	(yychar = YYEMPTY)
#define YYEMPTY		(-2)
#define YYEOF		0

#define YYACCEPT	goto yyacceptlab
#define YYABORT		goto yyabortlab
#define YYERROR		goto yyerrorlab


/* Like YYERROR except do call yyerror.  This remains here temporarily
   to ease the transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */

#define YYFAIL		goto yyerrlab

#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)					\
do								\
  if (yychar == YYEMPTY && yylen == 1)				\
    {								\
      yychar = (Token);						\
      yylval = (Value);						\
      yytoken = YYTRANSLATE (yychar);				\
      YYPOPSTACK (1);						\
      goto yybackup;						\
    }								\
  else								\
    {								\
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;							\
    }								\
while (YYID (0))


#define YYTERROR	1
#define YYERRCODE	256


/* YYLLOC_DEFAULT -- Set CURRENT to span from RHS[1] to RHS[N].
   If N is 0, then set CURRENT to the empty location which ends
   the previous symbol: RHS[0] (always defined).  */

#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#ifndef YYLLOC_DEFAULT
# define YYLLOC_DEFAULT(Current, Rhs, N)				\
    do									\
      if (YYID (N))                                                    \
	{								\
	  (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;	\
	  (Current).first_column = YYRHSLOC (Rhs, 1).first_column;	\
	  (Current).last_line    = YYRHSLOC (Rhs, N).last_line;		\
	  (Current).last_column  = YYRHSLOC (Rhs, N).last_column;	\
	}								\
      else								\
	{								\
	  (Current).first_line   = (Current).last_line   =		\
	    YYRHSLOC (Rhs, 0).last_line;				\
	  (Current).first_column = (Current).last_column =		\
	    YYRHSLOC (Rhs, 0).last_column;				\
	}								\
    while (YYID (0))
#endif


/* YY_LOCATION_PRINT -- Print the location on the stream.
   This macro was not mandated originally: define only if we know
   we won't break user code: when these are the locations we know.  */

#ifndef YY_LOCATION_PRINT
# if YYLTYPE_IS_TRIVIAL
#  define YY_LOCATION_PRINT(File, Loc)			\
     fprintf (File, "%d.%d-%d.%d",			\
	      (Loc).first_line, (Loc).first_column,	\
	      (Loc).last_line,  (Loc).last_column)
# else
#  define YY_LOCATION_PRINT(File, Loc) ((void) 0)
# endif
#endif


/* YYLEX -- calling `yylex' with the right arguments.  */

#ifdef YYLEX_PARAM
# define YYLEX yylex (YYLEX_PARAM)
#else
# define YYLEX yylex ()
#endif

/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)			\
do {						\
  if (yydebug)					\
    YYFPRINTF Args;				\
} while (YYID (0))

# define YY_SYMBOL_PRINT(Title, Type, Value, Location)			  \
do {									  \
  if (yydebug)								  \
    {									  \
      YYFPRINTF (stderr, "%s ", Title);					  \
      yy_symbol_print (stderr,						  \
		  Type, Value); \
      YYFPRINTF (stderr, "\n");						  \
    }									  \
} while (YYID (0))


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

/*ARGSUSED*/
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
#else
static void
yy_symbol_value_print (yyoutput, yytype, yyvaluep)
    FILE *yyoutput;
    int yytype;
    YYSTYPE const * const yyvaluep;
#endif
{
  if (!yyvaluep)
    return;
# ifdef YYPRINT
  if (yytype < YYNTOKENS)
    YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
# else
  YYUSE (yyoutput);
# endif
  switch (yytype)
    {
      default:
	break;
    }
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
#else
static void
yy_symbol_print (yyoutput, yytype, yyvaluep)
    FILE *yyoutput;
    int yytype;
    YYSTYPE const * const yyvaluep;
#endif
{
  if (yytype < YYNTOKENS)
    YYFPRINTF (yyoutput, "token %s (", yytname[yytype]);
  else
    YYFPRINTF (yyoutput, "nterm %s (", yytname[yytype]);

  yy_symbol_value_print (yyoutput, yytype, yyvaluep);
  YYFPRINTF (yyoutput, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
#else
static void
yy_stack_print (yybottom, yytop)
    yytype_int16 *yybottom;
    yytype_int16 *yytop;
#endif
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)				\
do {								\
  if (yydebug)							\
    yy_stack_print ((Bottom), (Top));				\
} while (YYID (0))


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_reduce_print (YYSTYPE *yyvsp, int yyrule)
#else
static void
yy_reduce_print (yyvsp, yyrule)
    YYSTYPE *yyvsp;
    int yyrule;
#endif
{
  int yynrhs = yyr2[yyrule];
  int yyi;
  unsigned long int yylno = yyrline[yyrule];
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
	     yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr, yyrhs[yyprhs[yyrule] + yyi],
		       &(yyvsp[(yyi + 1) - (yynrhs)])
		       		       );
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)		\
do {					\
  if (yydebug)				\
    yy_reduce_print (yyvsp, Rule); \
} while (YYID (0))

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef	YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif



#if YYERROR_VERBOSE

# ifndef yystrlen
#  if defined __GLIBC__ && defined _STRING_H
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static YYSIZE_T
yystrlen (const char *yystr)
#else
static YYSIZE_T
yystrlen (yystr)
    const char *yystr;
#endif
{
  YYSIZE_T yylen;
  for (yylen = 0; yystr[yylen]; yylen++)
    continue;
  return yylen;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static char *
yystpcpy (char *yydest, const char *yysrc)
#else
static char *
yystpcpy (yydest, yysrc)
    char *yydest;
    const char *yysrc;
#endif
{
  char *yyd = yydest;
  const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif

# ifndef yytnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for yyerror.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
yytnamerr (char *yyres, const char *yystr)
{
  if (*yystr == '"')
    {
      YYSIZE_T yyn = 0;
      char const *yyp = yystr;

      for (;;)
	switch (*++yyp)
	  {
	  case '\'':
	  case ',':
	    goto do_not_strip_quotes;

	  case '\\':
	    if (*++yyp != '\\')
	      goto do_not_strip_quotes;
	    /* Fall through.  */
	  default:
	    if (yyres)
	      yyres[yyn] = *yyp;
	    yyn++;
	    break;

	  case '"':
	    if (yyres)
	      yyres[yyn] = '\0';
	    return yyn;
	  }
    do_not_strip_quotes: ;
    }

  if (! yyres)
    return yystrlen (yystr);

  return yystpcpy (yyres, yystr) - yyres;
}
# endif

/* Copy into YYRESULT an error message about the unexpected token
   YYCHAR while in state YYSTATE.  Return the number of bytes copied,
   including the terminating null byte.  If YYRESULT is null, do not
   copy anything; just return the number of bytes that would be
   copied.  As a special case, return 0 if an ordinary "syntax error"
   message will do.  Return YYSIZE_MAXIMUM if overflow occurs during
   size calculation.  */
static YYSIZE_T
yysyntax_error (char *yyresult, int yystate, int yychar)
{
  int yyn = yypact[yystate];

  if (! (YYPACT_NINF < yyn && yyn <= YYLAST))
    return 0;
  else
    {
      int yytype = YYTRANSLATE (yychar);
      YYSIZE_T yysize0 = yytnamerr (0, yytname[yytype]);
      YYSIZE_T yysize = yysize0;
      YYSIZE_T yysize1;
      int yysize_overflow = 0;
      enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
      char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
      int yyx;

# if 0
      /* This is so xgettext sees the translatable formats that are
	 constructed on the fly.  */
      YY_("syntax error, unexpected %s");
      YY_("syntax error, unexpected %s, expecting %s");
      YY_("syntax error, unexpected %s, expecting %s or %s");
      YY_("syntax error, unexpected %s, expecting %s or %s or %s");
      YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s");
# endif
      char *yyfmt;
      char const *yyf;
      static char const yyunexpected[] = "syntax error, unexpected %s";
      static char const yyexpecting[] = ", expecting %s";
      static char const yyor[] = " or %s";
      char yyformat[sizeof yyunexpected
		    + sizeof yyexpecting - 1
		    + ((YYERROR_VERBOSE_ARGS_MAXIMUM - 2)
		       * (sizeof yyor - 1))];
      char const *yyprefix = yyexpecting;

      /* Start YYX at -YYN if negative to avoid negative indexes in
	 YYCHECK.  */
      int yyxbegin = yyn < 0 ? -yyn : 0;

      /* Stay within bounds of both yycheck and yytname.  */
      int yychecklim = YYLAST - yyn + 1;
      int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
      int yycount = 1;

      yyarg[0] = yytname[yytype];
      yyfmt = yystpcpy (yyformat, yyunexpected);

      for (yyx = yyxbegin; yyx < yyxend; ++yyx)
	if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR)
	  {
	    if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
	      {
		yycount = 1;
		yysize = yysize0;
		yyformat[sizeof yyunexpected - 1] = '\0';
		break;
	      }
	    yyarg[yycount++] = yytname[yyx];
	    yysize1 = yysize + yytnamerr (0, yytname[yyx]);
	    yysize_overflow |= (yysize1 < yysize);
	    yysize = yysize1;
	    yyfmt = yystpcpy (yyfmt, yyprefix);
	    yyprefix = yyor;
	  }

      yyf = YY_(yyformat);
      yysize1 = yysize + yystrlen (yyf);
      yysize_overflow |= (yysize1 < yysize);
      yysize = yysize1;

      if (yysize_overflow)
	return YYSIZE_MAXIMUM;

      if (yyresult)
	{
	  /* Avoid sprintf, as that infringes on the user's name space.
	     Don't have undefined behavior even if the translation
	     produced a string with the wrong number of "%s"s.  */
	  char *yyp = yyresult;
	  int yyi = 0;
	  while ((*yyp = *yyf) != '\0')
	    {
	      if (*yyp == '%' && yyf[1] == 's' && yyi < yycount)
		{
		  yyp += yytnamerr (yyp, yyarg[yyi++]);
		  yyf += 2;
		}
	      else
		{
		  yyp++;
		  yyf++;
		}
	    }
	}
      return yysize;
    }
}
#endif /* YYERROR_VERBOSE */


/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

/*ARGSUSED*/
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep)
#else
static void
yydestruct (yymsg, yytype, yyvaluep)
    const char *yymsg;
    int yytype;
    YYSTYPE *yyvaluep;
#endif
{
  YYUSE (yyvaluep);

  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);

  switch (yytype)
    {

      default:
	break;
    }
}

/* Prevent warnings from -Wmissing-prototypes.  */
#ifdef YYPARSE_PARAM
#if defined __STDC__ || defined __cplusplus
int yyparse (void *YYPARSE_PARAM);
#else
int yyparse ();
#endif
#else /* ! YYPARSE_PARAM */
#if defined __STDC__ || defined __cplusplus
int yyparse (void);
#else
int yyparse ();
#endif
#endif /* ! YYPARSE_PARAM */


/* The lookahead symbol.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;

/* Number of syntax errors so far.  */
int yynerrs;



/*-------------------------.
| yyparse or yypush_parse.  |
`-------------------------*/

#ifdef YYPARSE_PARAM
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
int
yyparse (void *YYPARSE_PARAM)
#else
int
yyparse (YYPARSE_PARAM)
    void *YYPARSE_PARAM;
#endif
#else /* ! YYPARSE_PARAM */
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
int
yyparse (void)
#else
int
yyparse ()

#endif
#endif
{


    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;

    /* The stacks and their tools:
       `yyss': related to states.
       `yyvs': related to semantic values.

       Refer to the stacks thru separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;

    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;

    YYSIZE_T yystacksize;

  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif

#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  yytoken = 0;
  yyss = yyssa;
  yyvs = yyvsa;
  yystacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */
  yyssp = yyss;
  yyvsp = yyvs;

  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
	/* Give user a chance to reallocate the stack.  Use copies of
	   these so that the &'s don't force the real ones into
	   memory.  */
	YYSTYPE *yyvs1 = yyvs;
	yytype_int16 *yyss1 = yyss;

	/* Each stack pointer address is followed by the size of the
	   data in use in that stack, in bytes.  This used to be a
	   conditional around just the two extra args, but that might
	   be undefined if yyoverflow is a macro.  */
	yyoverflow (YY_("memory exhausted"),
		    &yyss1, yysize * sizeof (*yyssp),
		    &yyvs1, yysize * sizeof (*yyvsp),
		    &yystacksize);

	yyss = yyss1;
	yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
	goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
	yystacksize = YYMAXDEPTH;

      {
	yytype_int16 *yyss1 = yyss;
	union yyalloc *yyptr =
	  (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
	if (! yyptr)
	  goto yyexhaustedlab;
	YYSTACK_RELOCATE (yyss_alloc, yyss);
	YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
	if (yyss1 != yyssa)
	  YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
		  (unsigned long int) yystacksize));

      if (yyss + yystacksize - 1 <= yyssp)
	YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;

/*-----------.
| yybackup.  |
`-----------*/
yybackup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yyn == YYPACT_NINF)
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = YYLEX;
    }

  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yyn == 0 || yyn == YYTABLE_NINF)
	goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

  /* Discard the shifted token.  */
  yychar = YYEMPTY;

  yystate = yyn;
  *++yyvsp = yylval;

  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     `$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 2:

/* Line 1455 of yacc.c  */
#line 195 ".\\semantic.y"
    { /* Create a Program node and attach children for globals and main */
        (yyval.ast) = createASTNode(AST_PROGRAM, NULL, 0, 0.0, '\0');
(yyval.ast)->children = (yyvsp[(1) - (3)].ast);
        addChild((yyval.ast), (yyvsp[(1) - (3)].ast));
        addChild((yyval.ast), (yyvsp[(2) - (3)].ast));
        ;}
    break;

  case 3:

/* Line 1455 of yacc.c  */
#line 201 ".\\semantic.y"
    { ;}
    break;

  case 4:

/* Line 1455 of yacc.c  */
#line 205 ".\\semantic.y"
    {/* For a list of declarations, link them as siblings */
                        (yyval.ast)->children = (yyvsp[(1) - (2)].ast);
                        addSibling((yyval.ast), (yyvsp[(2) - (2)].ast));;}
    break;

  case 5:

/* Line 1455 of yacc.c  */
#line 208 ".\\semantic.y"
    {(yyval.ast) = createASTNode(AST_GLOBAL_DECLARATIONS, NULL, 0, 0.0, '\0'); ;}
    break;

  case 6:

/* Line 1455 of yacc.c  */
#line 211 ".\\semantic.y"
    {(yyval.ast)->children = (yyvsp[(1) - (1)].ast)
;;}
    break;

  case 12:

/* Line 1455 of yacc.c  */
#line 222 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_TYPEDEF_DECLARATION, (yyvsp[(4) - (6)].stringValue), 0, 0.0, '\0');
                        /* Attach the type name, list specifier, and dimensions (if any) */
                        if ((yyvsp[(2) - (6)].ast)) addChild((yyval.ast), (yyvsp[(2) - (6)].ast));
                        if ((yyvsp[(3) - (6)].ast)) addChild((yyval.ast), (yyvsp[(3) - (6)].ast));
                        if ((yyvsp[(5) - (6)].ast)) addChild((yyval.ast), (yyvsp[(5) - (6)].ast));
                        /* Do your symbol table checks */
                        if (isDeclaredInScope(hashtbl, (yyvsp[(4) - (6)].stringValue), scope)) {
                            yyerror("Variable already declared in the current scope");
                        } else {
                            hashtbl_insert_debug((yyvsp[(4) - (6)].stringValue), scope);
                        }
                        ;}
    break;

  case 13:

/* Line 1455 of yacc.c  */
#line 237 ".\\semantic.y"
    { (yyval.ast)->children = (yyvsp[(1) - (1)].ast)
; ;}
    break;

  case 14:

/* Line 1455 of yacc.c  */
#line 240 ".\\semantic.y"
    {
                (yyval.ast) = createASTNode(AST_TYPE_NAME, (yyvsp[(1) - (1)].stringValue), 0, 0.0, '\0');
                hashtbl_insert_debug((yyvsp[(1) - (1)].stringValue), scope);
                ;}
    break;

  case 15:

/* Line 1455 of yacc.c  */
#line 245 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_STANDARD_TYPE, "char", TYPE_CHAR, 0.0, '\0'); ;}
    break;

  case 16:

/* Line 1455 of yacc.c  */
#line 246 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_STANDARD_TYPE, "int", TYPE_INT, 0.0, '\0'); ;}
    break;

  case 17:

/* Line 1455 of yacc.c  */
#line 247 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_STANDARD_TYPE, "float", TYPE_FLOAT, 0.0, '\0'); ;}
    break;

  case 18:

/* Line 1455 of yacc.c  */
#line 248 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_STANDARD_TYPE, "string", TYPE_STRING, 0.0, '\0'); ;}
    break;

  case 19:

/* Line 1455 of yacc.c  */
#line 249 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_STANDARD_TYPE, "void", TYPE_VOID, 0.0, '\0'); ;}
    break;

  case 20:

/* Line 1455 of yacc.c  */
#line 252 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_LISTSPEC, "list", 1, 0.0, '\0'); ;}
    break;

  case 21:

/* Line 1455 of yacc.c  */
#line 253 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_LISTSPEC, "not list", 0, 0.0, '\0'); ;}
    break;

  case 22:

/* Line 1455 of yacc.c  */
#line 256 ".\\semantic.y"
    {
         (yyval.ast)->children = (yyvsp[(1) - (2)].ast)
;
         addSibling((yyval.ast), (yyvsp[(2) - (2)].ast));
        ;}
    break;

  case 23:

/* Line 1455 of yacc.c  */
#line 261 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_DIMS, NULL, 0, 0.0, '\0'); ;}
    break;

  case 24:

/* Line 1455 of yacc.c  */
#line 264 ".\\semantic.y"
    {(yyval.ast) = createASTNode(AST_DIM, NULL, (yyvsp[(2) - (3)].intValue), 0.0, '\0');;}
    break;

  case 25:

/* Line 1455 of yacc.c  */
#line 265 ".\\semantic.y"
    {(yyval.ast) = createASTNode(AST_DIM, "empty", 0, 0.0, '\0');;}
    break;

  case 26:

/* Line 1455 of yacc.c  */
#line 269 ".\\semantic.y"
    {
                    if (!predicate_check_not_declared((yyvsp[(2) - (4)].stringValue), scope)) {
                        yyerror("Enum redeclaration: identifier already declared in current scope");
                    } else {
                        hashtbl_insert_debug((yyvsp[(2) - (4)].stringValue), scope);
                    }
                    ;}
    break;

  case 28:

/* Line 1455 of yacc.c  */
#line 282 ".\\semantic.y"
    { hashtbl_insert_debug((yyvsp[(3) - (4)].stringValue), scope);; ;}
    break;

  case 29:

/* Line 1455 of yacc.c  */
#line 283 ".\\semantic.y"
    { hashtbl_insert_debug((yyvsp[(1) - (2)].stringValue), scope); ;}
    break;

  case 31:

/* Line 1455 of yacc.c  */
#line 287 ".\\semantic.y"
    { ;}
    break;

  case 33:

/* Line 1455 of yacc.c  */
#line 291 ".\\semantic.y"
    {scope--; ;}
    break;

  case 38:

/* Line 1455 of yacc.c  */
#line 299 ".\\semantic.y"
    {
                (yyval.ast) = createASTNode(AST_EXPRESSION, "+", 0, 0.0, '\0');
                addChild((yyval.ast), (yyvsp[(1) - (3)].ast));
                addChild((yyval.ast), (yyvsp[(3) - (3)].ast));
                /* Insert type checking or semantic actions as needed */
            ;}
    break;

  case 39:

/* Line 1455 of yacc.c  */
#line 306 ".\\semantic.y"
    {
                (yyval.ast) = createASTNode(AST_EXPRESSION, "*", 0, 0.0, '\0');
                addChild((yyval.ast), (yyvsp[(1) - (3)].ast));
                addChild((yyval.ast), (yyvsp[(3) - (3)].ast));
                /* Insert type checking or semantic actions as needed */
            ;}
    break;

  case 50:

/* Line 1455 of yacc.c  */
#line 322 ".\\semantic.y"
    { (yyval.ast) = (yyvsp[(2) - (3)].ast); ;}
    break;

  case 54:

/* Line 1455 of yacc.c  */
#line 329 ".\\semantic.y"
    {
            {
                (yyval.ast) = createASTNode(AST_VARIABLE, ".", 0, 0.0, '\0');
                addChild((yyval.ast), (yyvsp[(1) - (3)].ast));
            }
            hashtbl_insert_debug((yyvsp[(3) - (3)].stringValue), scope);
         ;}
    break;

  case 56:

/* Line 1455 of yacc.c  */
#line 338 ".\\semantic.y"
    {
                (yyval.ast) = createASTNode(AST_VARIABLE, (yyvsp[(2) - (2)].stringValue), 0, 0.0, '\0');
                hashtbl_insert_debug((yyvsp[(2) - (2)].stringValue), scope);
            ;}
    break;

  case 57:

/* Line 1455 of yacc.c  */
#line 342 ".\\semantic.y"
    {(yyval.ast) = createASTNode(AST_VARIABLE, "this", 0, 0.0, '\0');;}
    break;

  case 60:

/* Line 1455 of yacc.c  */
#line 350 ".\\semantic.y"
    {
            if (!predicate_check_type_compatibility((yyvsp[(1) - (3)].ast), (yyvsp[(3) - (3)].ast))) {
                yyerror("Type mismatch in assignment");
            }
            /* Optionally, you could assign $$ the resulting type for later use */
            (yyval.ast)->children = (yyvsp[(1) - (3)].ast)
;  /* assuming the type of the assignment is that of the variable */
            ;}
    break;

  case 63:

/* Line 1455 of yacc.c  */
#line 362 ".\\semantic.y"
    { ;}
    break;

  case 71:

/* Line 1455 of yacc.c  */
#line 376 ".\\semantic.y"
    {
                    if (!predicate_check_not_declared((yyvsp[(2) - (4)].stringValue), scope)) {
                        yyerror("Class redeclaration: identifier already declared in current scope");
                    } else {
                        hashtbl_insert_debug((yyvsp[(2) - (4)].stringValue), scope);
                    }
                    ;}
    break;

  case 72:

/* Line 1455 of yacc.c  */
#line 385 ".\\semantic.y"
    {scope--; ;}
    break;

  case 73:

/* Line 1455 of yacc.c  */
#line 388 ".\\semantic.y"
    { hashtbl_insert_debug((yyvsp[(2) - (2)].stringValue), scope); ;}
    break;

  case 74:

/* Line 1455 of yacc.c  */
#line 389 ".\\semantic.y"
    { ;}
    break;

  case 77:

/* Line 1455 of yacc.c  */
#line 396 ".\\semantic.y"
    { scope++; ;}
    break;

  case 78:

/* Line 1455 of yacc.c  */
#line 397 ".\\semantic.y"
    { scope++; ;}
    break;

  case 79:

/* Line 1455 of yacc.c  */
#line 398 ".\\semantic.y"
    { scope++; ;}
    break;

  case 80:

/* Line 1455 of yacc.c  */
#line 399 ".\\semantic.y"
    { ;}
    break;

  case 86:

/* Line 1455 of yacc.c  */
#line 412 ".\\semantic.y"
    { yyerror("Missing semicolon in variable declaration; recovering from error"); ;}
    break;

  case 89:

/* Line 1455 of yacc.c  */
#line 420 ".\\semantic.y"
    { // verifys that the parse first evaluates the predicate before inserting the variable, to check if it doesnt already exist
                if (!predicate_check_not_declared((yyvsp[(2) - (3)].stringValue), scope)) {
                    yyerror("Variable redeclaration: identifier already declared in current scope");
                } else {
                    hashtbl_insert_debug((yyvsp[(2) - (3)].stringValue), scope);
                }
                ;}
    break;

  case 90:

/* Line 1455 of yacc.c  */
#line 429 ".\\semantic.y"
    {scope++; ;}
    break;

  case 91:

/* Line 1455 of yacc.c  */
#line 432 ".\\semantic.y"
    {hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 99:

/* Line 1455 of yacc.c  */
#line 453 ".\\semantic.y"
    {
                    if (!predicate_check_not_declared((yyvsp[(3) - (3)].stringValue), scope)) {
                        yyerror("Function redeclaration: identifier already declared in current scope");
                    } else {
                        hashtbl_insert_debug((yyvsp[(3) - (3)].stringValue), scope);
                    }
                    ;}
    break;

  case 105:

/* Line 1455 of yacc.c  */
#line 474 ".\\semantic.y"
    {
                    if (!predicate_check_not_declared((yyvsp[(2) - (4)].stringValue), scope)) {
                        yyerror("Union redeclaration: identifier already declared in current scope");
                    } else {
                        hashtbl_insert_debug((yyvsp[(2) - (4)].stringValue), scope);
                    }
                    ;}
    break;

  case 112:

/* Line 1455 of yacc.c  */
#line 498 ".\\semantic.y"
    { scope++; ;}
    break;

  case 113:

/* Line 1455 of yacc.c  */
#line 498 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 114:

/* Line 1455 of yacc.c  */
#line 499 ".\\semantic.y"
    { scope++; ;}
    break;

  case 115:

/* Line 1455 of yacc.c  */
#line 499 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 116:

/* Line 1455 of yacc.c  */
#line 500 ".\\semantic.y"
    { scope++; ;}
    break;

  case 117:

/* Line 1455 of yacc.c  */
#line 500 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 120:

/* Line 1455 of yacc.c  */
#line 507 ".\\semantic.y"
    { hashtbl_insert_debug((yyvsp[(4) - (4)].stringValue), scope); ;}
    break;

  case 121:

/* Line 1455 of yacc.c  */
#line 510 ".\\semantic.y"
    { hashtbl_insert_debug((yyvsp[(1) - (2)].stringValue), scope); ;}
    break;

  case 125:

/* Line 1455 of yacc.c  */
#line 518 ".\\semantic.y"
    { hashtbl_insert_debug((yyvsp[(2) - (2)].stringValue), scope); ;}
    break;

  case 130:

/* Line 1455 of yacc.c  */
#line 527 ".\\semantic.y"
    { /*empty*/;}
    break;

  case 131:

/* Line 1455 of yacc.c  */
#line 530 ".\\semantic.y"
    {scope++; ;}
    break;

  case 134:

/* Line 1455 of yacc.c  */
#line 535 ".\\semantic.y"
    { ;}
    break;

  case 138:

/* Line 1455 of yacc.c  */
#line 543 ".\\semantic.y"
    { (yyval.ast)->children = (yyvsp[(1) - (1)].ast)
; ;}
    break;

  case 145:

/* Line 1455 of yacc.c  */
#line 551 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_CONTINUE, NULL, 0, 0.0, '\0'); ;}
    break;

  case 146:

/* Line 1455 of yacc.c  */
#line 552 ".\\semantic.y"
    { (yyval.ast) = createASTNode(AST_BREAK, NULL, 0, 0.0, '\0'); ;}
    break;

  case 147:

/* Line 1455 of yacc.c  */
#line 553 ".\\semantic.y"
    {(yyval.ast) = createASTNode(AST_EXPRESSION_STATEMENT, NULL, 0, 0.0, '\0');;}
    break;

  case 149:

/* Line 1455 of yacc.c  */
#line 558 ".\\semantic.y"
    { yyerror("Invalid expression statement; recovering from error"); ;}
    break;

  case 150:

/* Line 1455 of yacc.c  */
#line 562 ".\\semantic.y"
    { 
                                    (yyval.ast) = createASTNode(AST_IF_STATEMENT, NULL, 0, 0.0, '\0');
                                    /* Add the condition and then-statement as children */
                                    addChild((yyval.ast), (yyvsp[(3) - (6)].ast));
                                    addChild((yyval.ast), (yyvsp[(5) - (6)].ast));
                                    if ((yyvsp[(6) - (6)].ast) != NULL)
                                        addChild((yyval.ast), (yyvsp[(6) - (6)].ast));  /* Else branch if it exists */
                                    hashtbl_get(hashtbl, scope);
                                    scope--;   
                                 ;}
    break;

  case 151:

/* Line 1455 of yacc.c  */
#line 573 ".\\semantic.y"
    { (yyval.ast) = (yyvsp[(2) - (2)].ast); ;}
    break;

  case 152:

/* Line 1455 of yacc.c  */
#line 574 ".\\semantic.y"
    { ;}
    break;

  case 153:

/* Line 1455 of yacc.c  */
#line 577 ".\\semantic.y"
    { scope++; ;}
    break;

  case 154:

/* Line 1455 of yacc.c  */
#line 577 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 155:

/* Line 1455 of yacc.c  */
#line 580 ".\\semantic.y"
    { scope++; ;}
    break;

  case 156:

/* Line 1455 of yacc.c  */
#line 580 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 158:

/* Line 1455 of yacc.c  */
#line 584 ".\\semantic.y"
    { ;}
    break;

  case 159:

/* Line 1455 of yacc.c  */
#line 587 ".\\semantic.y"
    { scope++; ;}
    break;

  case 160:

/* Line 1455 of yacc.c  */
#line 587 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 161:

/* Line 1455 of yacc.c  */
#line 590 ".\\semantic.y"
    {hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 166:

/* Line 1455 of yacc.c  */
#line 597 ".\\semantic.y"
    { ;}
    break;

  case 167:

/* Line 1455 of yacc.c  */
#line 600 ".\\semantic.y"
    {scope++; ;}
    break;

  case 183:

/* Line 1455 of yacc.c  */
#line 634 ".\\semantic.y"
    { scope++; ;}
    break;

  case 184:

/* Line 1455 of yacc.c  */
#line 634 ".\\semantic.y"
    { hashtbl_get(hashtbl, scope); scope--; ;}
    break;

  case 185:

/* Line 1455 of yacc.c  */
#line 638 ".\\semantic.y"
    {
                (yyval.ast) = createASTNode(AST_MAIN_FUNCTION, NULL, 0, 0.0, '\0');
                addChild((yyval.ast), (yyvsp[(1) - (4)].ast));
                addChild((yyval.ast), (yyvsp[(3) - (4)].ast));
                hashtbl_get(hashtbl, scope); scope--;
                ;}
    break;

  case 186:

/* Line 1455 of yacc.c  */
#line 647 ".\\semantic.y"
    {
                (yyval.ast) = createASTNode(AST_MAIN_HEADER, "main", 0, 0.0, '\0');
                scope++;
            ;}
    break;



/* Line 1455 of yacc.c  */
#line 2590 "semantic.tab.c"
      default: break;
    }
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);

  *++yyvsp = yyval;

  /* Now `shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];

  goto yynewstate;


/*------------------------------------.
| yyerrlab -- here on detecting error |
`------------------------------------*/
yyerrlab:
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
      {
	YYSIZE_T yysize = yysyntax_error (0, yystate, yychar);
	if (yymsg_alloc < yysize && yymsg_alloc < YYSTACK_ALLOC_MAXIMUM)
	  {
	    YYSIZE_T yyalloc = 2 * yysize;
	    if (! (yysize <= yyalloc && yyalloc <= YYSTACK_ALLOC_MAXIMUM))
	      yyalloc = YYSTACK_ALLOC_MAXIMUM;
	    if (yymsg != yymsgbuf)
	      YYSTACK_FREE (yymsg);
	    yymsg = (char *) YYSTACK_ALLOC (yyalloc);
	    if (yymsg)
	      yymsg_alloc = yyalloc;
	    else
	      {
		yymsg = yymsgbuf;
		yymsg_alloc = sizeof yymsgbuf;
	      }
	  }

	if (0 < yysize && yysize <= yymsg_alloc)
	  {
	    (void) yysyntax_error (yymsg, yystate, yychar);
	    yyerror (yymsg);
	  }
	else
	  {
	    yyerror (YY_("syntax error"));
	    if (yysize != 0)
	      goto yyexhaustedlab;
	  }
      }
#endif
    }



  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
	 error, discard it.  */

      if (yychar <= YYEOF)
	{
	  /* Return failure if at end of input.  */
	  if (yychar == YYEOF)
	    YYABORT;
	}
      else
	{
	  yydestruct ("Error: discarding",
		      yytoken, &yylval);
	  yychar = YYEMPTY;
	}
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;

  /* Do not reclaim the symbols of the rule which action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;	/* Each real token shifted decrements this.  */

  for (;;)
    {
      yyn = yypact[yystate];
      if (yyn != YYPACT_NINF)
	{
	  yyn += YYTERROR;
	  if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
	    {
	      yyn = yytable[yyn];
	      if (0 < yyn)
		break;
	    }
	}

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
	YYABORT;


      yydestruct ("Error: popping",
		  yystos[yystate], yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  *++yyvsp = yylval;


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

#if !defined(yyoverflow) || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif

yyreturn:
  if (yychar != YYEMPTY)
     yydestruct ("Cleanup: discarding lookahead",
		 yytoken, &yylval);
  /* Do not reclaim the symbols of the rule which action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
		  yystos[*yyssp], yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  /* Make sure YYID is used.  */
  return YYID (yyresult);
}



/* Line 1675 of yacc.c  */
#line 654 ".\\semantic.y"


int main(int argc, char *argv[]) { // Main function
    int token;

    if (!(hashtbl = hashtbl_create(10, NULL))){ //initialize hashtable
    puts("Error, failed to initialize hashtable");
    exit(EXIT_FAILURE);
  }
  int scope =0;

    if (argc > 1) { // Check if an input file is provided
        yyin = fopen(argv[1], "r");
        if (yyin == NULL) {
            perror("Error opening file");
            return -1;
        }
    } else {
        fprintf(stderr, "No input file provided.\n");
        return -1;
    }

    yyparse();  // Call the parser

    fclose(yyin);  // Close the file after parsing
    hashtbl_get(hashtbl, scope); //get the hashtable
    hashtbl_destroy(hashtbl);
    return 0;
}

void yyerror(const char *s) {
    extern int yylineno;  // lexer input line number
    extern char current_line[];  // lexer input line
    error_count++;  // error counter

    fprintf(stderr, "Syntax error at line %d: %s\n", yylineno, s);  //print error message

    if (error_count >= 5) {
        fprintf(stderr, "Too many syntax errors. Aborting parsing.\n");
        exit(1);  // terminate program
    }
}



